# coding: utf-8

"""
    v10 - Retailer API

    The bol.com API for retailers.  # Authentication Our API requires authentication via OAuth2. The detailed steps to authenticate are explained [here](https://api.bol.com/retailer/public/Retailer-API/authentication.html)   # Demo scenarios Our API specification includes examples of the responses you can expect. For more information as well as more examples, we refer you to the following resources:   - [Demo environment](https://api.bol.com/retailer/public/Retailer-API/demo/demo.html) - [Demo scenarios](https://api.bol.com/retailer/public/Retailer-API/demo/v10-index.html) 

    The version of the OpenAPI document: 10.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.product_content_api import ProductContentApi


class TestProductContentApi(unittest.TestCase):
    """ProductContentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProductContentApi()

    def tearDown(self) -> None:
        pass

    def test_get_catalog_product(self) -> None:
        """Test case for get_catalog_product

        Get catalog product details by EAN
        """
        pass

    def test_get_chunk_recommendations(self) -> None:
        """Test case for get_chunk_recommendations

        Get chunk recommendations
        """
        pass

    def test_get_upload_report(self) -> None:
        """Test case for get_upload_report

        Get an upload report by upload id
        """
        pass

    def test_post_product_content(self) -> None:
        """Test case for post_product_content

        Create content for a product
        """
        pass


if __name__ == '__main__':
    unittest.main()
