# coding: utf-8

"""
    v10 - Retailer API

    The bol.com API for retailers.  # Authentication Our API requires authentication via OAuth2. The detailed steps to authenticate are explained [here](https://api.bol.com/retailer/public/Retailer-API/authentication.html)   # Demo scenarios Our API specification includes examples of the responses you can expect. For more information as well as more examples, we refer you to the following resources:   - [Demo environment](https://api.bol.com/retailer/public/Retailer-API/demo/demo.html) - [Demo scenarios](https://api.bol.com/retailer/public/Retailer-API/demo/v10-index.html) 

    The version of the OpenAPI document: 10.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.offers_api import OffersApi


class TestOffersApi(unittest.TestCase):
    """OffersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OffersApi()

    def tearDown(self) -> None:
        pass

    def test_delete_offer(self) -> None:
        """Test case for delete_offer

        Delete offer by id
        """
        pass

    def test_get_offer(self) -> None:
        """Test case for get_offer

        Retrieve an offer by its offer id
        """
        pass

    def test_get_offer_export(self) -> None:
        """Test case for get_offer_export

        Retrieve an offer export file by report id
        """
        pass

    def test_get_unpublished_offer_report(self) -> None:
        """Test case for get_unpublished_offer_report

        Retrieve an unpublished offer report by report id
        """
        pass

    def test_post_offer(self) -> None:
        """Test case for post_offer

        Create a new offer
        """
        pass

    def test_post_offer_export(self) -> None:
        """Test case for post_offer_export

        Request an offer export file
        """
        pass

    def test_post_unpublished_offer_report(self) -> None:
        """Test case for post_unpublished_offer_report

        Request an unpublished offer report
        """
        pass

    def test_put_offer(self) -> None:
        """Test case for put_offer

        Update an offer
        """
        pass

    def test_update_offer_price(self) -> None:
        """Test case for update_offer_price

        Update price(s) for offer by id
        """
        pass

    def test_update_offer_stock(self) -> None:
        """Test case for update_offer_stock

        Update stock for offer by id
        """
        pass


if __name__ == '__main__':
    unittest.main()
