# coding: utf-8

"""
    v10 - Retailer API

    The bol.com API for retailers.  # Authentication Our API requires authentication via OAuth2. The detailed steps to authenticate are explained [here](https://api.bol.com/retailer/public/Retailer-API/authentication.html)   # Demo scenarios Our API specification includes examples of the responses you can expect. For more information as well as more examples, we refer you to the following resources:   - [Demo environment](https://api.bol.com/retailer/public/Retailer-API/demo/demo.html) - [Demo scenarios](https://api.bol.com/retailer/public/Retailer-API/demo/v10-index.html) 

    The version of the OpenAPI document: 10.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.insights_api import InsightsApi


class TestInsightsApi(unittest.TestCase):
    """InsightsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InsightsApi()

    def tearDown(self) -> None:
        pass

    def test_get_offer_insights(self) -> None:
        """Test case for get_offer_insights

        Get offer insights
        """
        pass

    def test_get_performance_indicators(self) -> None:
        """Test case for get_performance_indicators

        Get performance indicators
        """
        pass

    def test_get_product_ranks(self) -> None:
        """Test case for get_product_ranks

        Get product ranks
        """
        pass

    def test_get_sales_forecast(self) -> None:
        """Test case for get_sales_forecast

        Get sales forecast
        """
        pass

    def test_get_search_terms(self) -> None:
        """Test case for get_search_terms

        Get search terms
        """
        pass


if __name__ == '__main__':
    unittest.main()
