# coding: utf-8

"""
    v10 - Retailer API

    The bol.com API for retailers.  # Authentication Our API requires authentication via OAuth2. The detailed steps to authenticate are explained [here](https://api.bol.com/retailer/public/Retailer-API/authentication.html)   # Demo scenarios Our API specification includes examples of the responses you can expect. For more information as well as more examples, we refer you to the following resources:   - [Demo environment](https://api.bol.com/retailer/public/Retailer-API/demo/demo.html) - [Demo scenarios](https://api.bol.com/retailer/public/Retailer-API/demo/v10-index.html) 

    The version of the OpenAPI document: 10.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.subscriptions_api import SubscriptionsApi


class TestSubscriptionsApi(unittest.TestCase):
    """SubscriptionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubscriptionsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_push_notification_subscription(self) -> None:
        """Test case for delete_push_notification_subscription

        Remove Event Notification Subscription
        """
        pass

    def test_get_push_notification_subscription(self) -> None:
        """Test case for get_push_notification_subscription

        Retrieve Specific Event Notification Subscription (BETA)
        """
        pass

    def test_get_push_notification_subscriptions(self) -> None:
        """Test case for get_push_notification_subscriptions

        Retrieve Event Notification Subscriptions (BETA)
        """
        pass

    def test_get_subscription_keys(self) -> None:
        """Test case for get_subscription_keys

        Retrieve public keys for push notification signature validation.
        """
        pass

    def test_post_push_notification_subscription(self) -> None:
        """Test case for post_push_notification_subscription

        Create Event Notification Subscription (BETA)
        """
        pass

    def test_post_test_push_notification(self) -> None:
        """Test case for post_test_push_notification

        Send test push notification for subscriptions
        """
        pass

    def test_put_push_notification_subscription(self) -> None:
        """Test case for put_push_notification_subscription

        Update Event Notification Subscription (BETA)
        """
        pass


if __name__ == '__main__':
    unittest.main()
