# coding: utf-8

"""
    v10 - Retailer API

    The bol.com API for retailers.  # Authentication Our API requires authentication via OAuth2. The detailed steps to authenticate are explained [here](https://api.bol.com/retailer/public/Retailer-API/authentication.html)   # Demo scenarios Our API specification includes examples of the responses you can expect. For more information as well as more examples, we refer you to the following resources:   - [Demo environment](https://api.bol.com/retailer/public/Retailer-API/demo/demo.html) - [Demo scenarios](https://api.bol.com/retailer/public/Retailer-API/demo/v10-index.html) 

    The version of the OpenAPI document: 10.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.reduced_order import ReducedOrder

class TestReducedOrder(unittest.TestCase):
    """ReducedOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReducedOrder:
        """Test ReducedOrder
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReducedOrder`
        """
        model = ReducedOrder()
        if include_optional:
            return ReducedOrder(
                order_id = 'A2K8290LP8',
                order_placed_date_time = '2017-02-09T12:39:48+01:00',
                order_items = [
                    openapi_client.models.reduced_order_item.ReducedOrderItem(
                        order_item_id = '2012345678', 
                        ean = '0000007740404', 
                        fulfilment_method = 'FBR', 
                        fulfilment_status = 'OPEN', 
                        quantity = 10, 
                        quantity_shipped = 10, 
                        quantity_cancelled = 0, 
                        cancellation_request = False, 
                        latest_changed_date_time = '2017-02-09T12:39:48+01:00', )
                    ]
            )
        else:
            return ReducedOrder(
                order_id = 'A2K8290LP8',
                order_placed_date_time = '2017-02-09T12:39:48+01:00',
                order_items = [
                    openapi_client.models.reduced_order_item.ReducedOrderItem(
                        order_item_id = '2012345678', 
                        ean = '0000007740404', 
                        fulfilment_method = 'FBR', 
                        fulfilment_status = 'OPEN', 
                        quantity = 10, 
                        quantity_shipped = 10, 
                        quantity_cancelled = 0, 
                        cancellation_request = False, 
                        latest_changed_date_time = '2017-02-09T12:39:48+01:00', )
                    ],
        )
        """

    def testReducedOrder(self):
        """Test ReducedOrder"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
