# coding: utf-8

"""
    v10 - Retailer API

    The bol.com API for retailers.  # Authentication Our API requires authentication via OAuth2. The detailed steps to authenticate are explained [here](https://api.bol.com/retailer/public/Retailer-API/authentication.html)   # Demo scenarios Our API specification includes examples of the responses you can expect. For more information as well as more examples, we refer you to the following resources:   - [Demo environment](https://api.bol.com/retailer/public/Retailer-API/demo/demo.html) - [Demo scenarios](https://api.bol.com/retailer/public/Retailer-API/demo/v10-index.html) 

    The version of the OpenAPI document: 10.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.reduced_shipment import ReducedShipment

class TestReducedShipment(unittest.TestCase):
    """ReducedShipment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReducedShipment:
        """Test ReducedShipment
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReducedShipment`
        """
        model = ReducedShipment()
        if include_optional:
            return ReducedShipment(
                shipment_id = '541757635',
                shipment_date_time = '2018-04-17T10:55:37+02:00',
                shipment_reference = 'BOLCOM001',
                order = openapi_client.models.reduced_shipment_order.ReducedShipmentOrder(
                    order_id = '4123456789', 
                    order_placed_date_time = '2018-04-17T10:55:37+02:00', ),
                shipment_items = [
                    openapi_client.models.reduced_shipment_item.ReducedShipmentItem(
                        order_item_id = '1234567891', 
                        ean = '0000007740404', )
                    ],
                transport = openapi_client.models.reduced_transport.ReducedTransport(
                    transport_id = '312778947', )
            )
        else:
            return ReducedShipment(
                shipment_id = '541757635',
                shipment_reference = 'BOLCOM001',
                order = openapi_client.models.reduced_shipment_order.ReducedShipmentOrder(
                    order_id = '4123456789', 
                    order_placed_date_time = '2018-04-17T10:55:37+02:00', ),
                shipment_items = [
                    openapi_client.models.reduced_shipment_item.ReducedShipmentItem(
                        order_item_id = '1234567891', 
                        ean = '0000007740404', )
                    ],
                transport = openapi_client.models.reduced_transport.ReducedTransport(
                    transport_id = '312778947', ),
        )
        """

    def testReducedShipment(self):
        """Test ReducedShipment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
