# coding: utf-8

"""
    v10 - Retailer API

    The bol.com API for retailers.  # Authentication Our API requires authentication via OAuth2. The detailed steps to authenticate are explained [here](https://api.bol.com/retailer/public/Retailer-API/authentication.html)   # Demo scenarios Our API specification includes examples of the responses you can expect. For more information as well as more examples, we refer you to the following resources:   - [Demo environment](https://api.bol.com/retailer/public/Retailer-API/demo/demo.html) - [Demo scenarios](https://api.bol.com/retailer/public/Retailer-API/demo/v10-index.html) 

    The version of the OpenAPI document: 10.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.invoice_requests_response import InvoiceRequestsResponse

class TestInvoiceRequestsResponse(unittest.TestCase):
    """InvoiceRequestsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvoiceRequestsResponse:
        """Test InvoiceRequestsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvoiceRequestsResponse`
        """
        model = InvoiceRequestsResponse()
        if include_optional:
            return InvoiceRequestsResponse(
                invoice_requests = [
                    openapi_client.models.invoice_requests.InvoiceRequests(
                        shipment_id = '987654', 
                        order_id = '4691862037', 
                        customer_account_number = '3004850316', 
                        billing_details = openapi_client.models.invoice_requests_billing_details.InvoiceRequestsBillingDetails(
                            salutation = 'MALE', 
                            first_name = 'Billie', 
                            surname = 'Jansen', 
                            street_name = 'Dorpstraat', 
                            house_number = '1', 
                            house_number_extension = 'B', 
                            zip_code = '1111ZZ', 
                            city = 'Utrecht', 
                            country_code = 'NL', 
                            company = 'bol.com', 
                            vat_number = 'NL999999999B99', 
                            kvk_number = '99887766', ), 
                        products = [
                            openapi_client.models.invoice_requests_products.InvoiceRequestsProducts(
                                description = 'Eucerin Hyaluron-filler', 
                                quantity = 56, 
                                unit_price = 10, )
                            ], 
                        status = 'INVOICE_REQUESTED', 
                        status_transitions = [
                            openapi_client.models.status_transitions.StatusTransitions(
                                status = 'INVOICE_REQUESTED', 
                                status_date_time = '2020-12-09T12:34:56+01:00', )
                            ], )
                    ]
            )
        else:
            return InvoiceRequestsResponse(
                invoice_requests = [
                    openapi_client.models.invoice_requests.InvoiceRequests(
                        shipment_id = '987654', 
                        order_id = '4691862037', 
                        customer_account_number = '3004850316', 
                        billing_details = openapi_client.models.invoice_requests_billing_details.InvoiceRequestsBillingDetails(
                            salutation = 'MALE', 
                            first_name = 'Billie', 
                            surname = 'Jansen', 
                            street_name = 'Dorpstraat', 
                            house_number = '1', 
                            house_number_extension = 'B', 
                            zip_code = '1111ZZ', 
                            city = 'Utrecht', 
                            country_code = 'NL', 
                            company = 'bol.com', 
                            vat_number = 'NL999999999B99', 
                            kvk_number = '99887766', ), 
                        products = [
                            openapi_client.models.invoice_requests_products.InvoiceRequestsProducts(
                                description = 'Eucerin Hyaluron-filler', 
                                quantity = 56, 
                                unit_price = 10, )
                            ], 
                        status = 'INVOICE_REQUESTED', 
                        status_transitions = [
                            openapi_client.models.status_transitions.StatusTransitions(
                                status = 'INVOICE_REQUESTED', 
                                status_date_time = '2020-12-09T12:34:56+01:00', )
                            ], )
                    ],
        )
        """

    def testInvoiceRequestsResponse(self):
        """Test InvoiceRequestsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
