# coding: utf-8

"""
    v10 - Retailer API

    The bol.com API for retailers.  # Authentication Our API requires authentication via OAuth2. The detailed steps to authenticate are explained [here](https://api.bol.com/retailer/public/Retailer-API/authentication.html)   # Demo scenarios Our API specification includes examples of the responses you can expect. For more information as well as more examples, we refer you to the following resources:   - [Demo environment](https://api.bol.com/retailer/public/Retailer-API/demo/demo.html) - [Demo scenarios](https://api.bol.com/retailer/public/Retailer-API/demo/v10-index.html) 

    The version of the OpenAPI document: 10.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.reduced_return_item import ReducedReturnItem

class TestReducedReturnItem(unittest.TestCase):
    """ReducedReturnItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReducedReturnItem:
        """Test ReducedReturnItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReducedReturnItem`
        """
        model = ReducedReturnItem()
        if include_optional:
            return ReducedReturnItem(
                rma_id = '31234567',
                order_id = '4012345678',
                ean = '9789076174082',
                expected_quantity = 1,
                return_reason = openapi_client.models.return_reason.ReturnReason(
                    main_reason = 'Niet naar verwachting', 
                    detailed_reason = 'Niet naar verwachting', 
                    customer_comments = 'Lorem Ipsum', ),
                handled = True,
                processing_results = [
                    openapi_client.models.return_processing_result.ReturnProcessingResult(
                        quantity = 1, 
                        processing_result = 'ACCEPTED', 
                        handling_result = 'RETURN_RECEIVED', 
                        processing_date_time = '2018-04-17T10:55:37+02:00', )
                    ]
            )
        else:
            return ReducedReturnItem(
                rma_id = '31234567',
                order_id = '4012345678',
                ean = '9789076174082',
                expected_quantity = 1,
                return_reason = openapi_client.models.return_reason.ReturnReason(
                    main_reason = 'Niet naar verwachting', 
                    detailed_reason = 'Niet naar verwachting', 
                    customer_comments = 'Lorem Ipsum', ),
                handled = True,
                processing_results = [
                    openapi_client.models.return_processing_result.ReturnProcessingResult(
                        quantity = 1, 
                        processing_result = 'ACCEPTED', 
                        handling_result = 'RETURN_RECEIVED', 
                        processing_date_time = '2018-04-17T10:55:37+02:00', )
                    ],
        )
        """

    def testReducedReturnItem(self):
        """Test ReducedReturnItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
