# coding: utf-8

"""
    v10 - Retailer API

    The bol.com API for retailers.  # Authentication Our API requires authentication via OAuth2. The detailed steps to authenticate are explained [here](https://api.bol.com/retailer/public/Retailer-API/authentication.html)   # Demo scenarios Our API specification includes examples of the responses you can expect. For more information as well as more examples, we refer you to the following resources:   - [Demo environment](https://api.bol.com/retailer/public/Retailer-API/demo/demo.html) - [Demo scenarios](https://api.bol.com/retailer/public/Retailer-API/demo/v10-index.html) 

    The version of the OpenAPI document: 10.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.bulk_commission_response import BulkCommissionResponse

class TestBulkCommissionResponse(unittest.TestCase):
    """BulkCommissionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BulkCommissionResponse:
        """Test BulkCommissionResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkCommissionResponse`
        """
        model = BulkCommissionResponse()
        if include_optional:
            return BulkCommissionResponse(
                commissions = [
                    openapi_client.models.commission.Commission(
                        ean = '0000007740404', 
                        condition = 'NEW', 
                        unit_price = 59.0, 
                        fixed_amount = 0.99, 
                        percentage = 15, 
                        total_cost = 6.85, 
                        total_cost_without_reduction = 9.84, 
                        reductions = [
                            openapi_client.models.reduction.Reduction(
                                maximum_price = 60.0, 
                                cost_reduction = 2.99, 
                                start_date = 'Mon Jan 01 00:00:00 UTC 2018', 
                                end_date = 'Tue Jan 30 00:00:00 UTC 2018', )
                            ], )
                    ]
            )
        else:
            return BulkCommissionResponse(
                commissions = [
                    openapi_client.models.commission.Commission(
                        ean = '0000007740404', 
                        condition = 'NEW', 
                        unit_price = 59.0, 
                        fixed_amount = 0.99, 
                        percentage = 15, 
                        total_cost = 6.85, 
                        total_cost_without_reduction = 9.84, 
                        reductions = [
                            openapi_client.models.reduction.Reduction(
                                maximum_price = 60.0, 
                                cost_reduction = 2.99, 
                                start_date = 'Mon Jan 01 00:00:00 UTC 2018', 
                                end_date = 'Tue Jan 30 00:00:00 UTC 2018', )
                            ], )
                    ],
        )
        """

    def testBulkCommissionResponse(self):
        """Test BulkCommissionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
