# coding: utf-8

"""
    v10 - Retailer API

    The bol.com API for retailers.  # Authentication Our API requires authentication via OAuth2. The detailed steps to authenticate are explained [here](https://api.bol.com/retailer/public/Retailer-API/authentication.html)   # Demo scenarios Our API specification includes examples of the responses you can expect. For more information as well as more examples, we refer you to the following resources:   - [Demo environment](https://api.bol.com/retailer/public/Retailer-API/demo/demo.html) - [Demo scenarios](https://api.bol.com/retailer/public/Retailer-API/demo/v10-index.html) 

    The version of the OpenAPI document: 10.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class InvalidReplenishmentLine(BaseModel):
    """
    InvalidReplenishmentLine
    """ # noqa: E501
    type: StrictStr = Field(description="Type of invalid replenishment line, in case the BSKU and/or EAN cannot be determined for this replenishment line.")
    quantity_announced: StrictInt = Field(description="The amount of announced quantity for this replenishment line.", alias="quantityAnnounced")
    quantity_received: StrictInt = Field(description="The amount of received quantity for this replenishment line.", alias="quantityReceived")
    quantity_in_progress: StrictInt = Field(description="The amount of quantity that is still in progress at the warehouse for this replenishment line.", alias="quantityInProgress")
    quantity_with_graded_state: StrictInt = Field(description="The quantity within this shipment line that has a graded (unsalable) state.", alias="quantityWithGradedState")
    quantity_with_regular_state: StrictInt = Field(description="The quantity within this shipment line that has a regular (salable) state.", alias="quantityWithRegularState")
    __properties: ClassVar[List[str]] = ["type", "quantityAnnounced", "quantityReceived", "quantityInProgress", "quantityWithGradedState", "quantityWithRegularState"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['UNKNOWN_FBB_PRODUCT', 'UNKNOWN_EAN_INVENTORY_RELATION']):
            raise ValueError("must be one of enum values ('UNKNOWN_FBB_PRODUCT', 'UNKNOWN_EAN_INVENTORY_RELATION')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InvalidReplenishmentLine from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InvalidReplenishmentLine from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "quantityAnnounced": obj.get("quantityAnnounced"),
            "quantityReceived": obj.get("quantityReceived"),
            "quantityInProgress": obj.get("quantityInProgress"),
            "quantityWithGradedState": obj.get("quantityWithGradedState"),
            "quantityWithRegularState": obj.get("quantityWithRegularState")
        })
        return _obj


