# coding: utf-8

"""
    v10 - Retailer API

    The bol.com API for retailers.  # Authentication Our API requires authentication via OAuth2. The detailed steps to authenticate are explained [here](https://api.bol.com/retailer/public/Retailer-API/authentication.html)   # Demo scenarios Our API specification includes examples of the responses you can expect. For more information as well as more examples, we refer you to the following resources:   - [Demo environment](https://api.bol.com/retailer/public/Retailer-API/demo/demo.html) - [Demo scenarios](https://api.bol.com/retailer/public/Retailer-API/demo/v10-index.html) 

    The version of the OpenAPI document: 10.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.delivery_information import DeliveryInformation
from openapi_client.models.invalid_replenishment_line import InvalidReplenishmentLine
from openapi_client.models.load_carrier import LoadCarrier
from openapi_client.models.pickup_appointment import PickupAppointment
from openapi_client.models.replenishment_line import ReplenishmentLine
from openapi_client.models.state_transition import StateTransition
from typing import Optional, Set
from typing_extensions import Self

class ReplenishmentResponse(BaseModel):
    """
    ReplenishmentResponse
    """ # noqa: E501
    replenishment_id: StrictStr = Field(description="The unique identifier of the replenishment.", alias="replenishmentId")
    creation_date_time: datetime = Field(description="The date and time when this replenishment was created. In ISO 8601 format.", alias="creationDateTime")
    reference: StrictStr = Field(description="Custom user defined reference to identify the replenishment.")
    labeling_by_bol: StrictBool = Field(description="Indicates whether the replenishment will be labeled by bol.com or not.", alias="labelingByBol")
    state: StrictStr = Field(description="Indicates the state of this replenishment order.")
    delivery_information: DeliveryInformation = Field(alias="deliveryInformation")
    pickup_appointment: Optional[PickupAppointment] = Field(default=None, alias="pickupAppointment")
    number_of_load_carriers: Optional[StrictInt] = Field(default=None, description="The number of load carriers in this shipment.", alias="numberOfLoadCarriers")
    load_carriers: List[LoadCarrier] = Field(alias="loadCarriers")
    lines: List[ReplenishmentLine]
    invalid_lines: List[InvalidReplenishmentLine] = Field(alias="invalidLines")
    state_transitions: List[StateTransition] = Field(alias="stateTransitions")
    __properties: ClassVar[List[str]] = ["replenishmentId", "creationDateTime", "reference", "labelingByBol", "state", "deliveryInformation", "pickupAppointment", "numberOfLoadCarriers", "loadCarriers", "lines", "invalidLines", "stateTransitions"]

    @field_validator('state')
    def state_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ANNOUNCED', 'IN_TRANSIT', 'ARRIVED_AT_WH', 'IN_PROGRESS_AT_WH', 'CANCELLED', 'DONE']):
            raise ValueError("must be one of enum values ('ANNOUNCED', 'IN_TRANSIT', 'ARRIVED_AT_WH', 'IN_PROGRESS_AT_WH', 'CANCELLED', 'DONE')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReplenishmentResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of delivery_information
        if self.delivery_information:
            _dict['deliveryInformation'] = self.delivery_information.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pickup_appointment
        if self.pickup_appointment:
            _dict['pickupAppointment'] = self.pickup_appointment.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in load_carriers (list)
        _items = []
        if self.load_carriers:
            for _item in self.load_carriers:
                if _item:
                    _items.append(_item.to_dict())
            _dict['loadCarriers'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in lines (list)
        _items = []
        if self.lines:
            for _item in self.lines:
                if _item:
                    _items.append(_item.to_dict())
            _dict['lines'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in invalid_lines (list)
        _items = []
        if self.invalid_lines:
            for _item in self.invalid_lines:
                if _item:
                    _items.append(_item.to_dict())
            _dict['invalidLines'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in state_transitions (list)
        _items = []
        if self.state_transitions:
            for _item in self.state_transitions:
                if _item:
                    _items.append(_item.to_dict())
            _dict['stateTransitions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReplenishmentResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "replenishmentId": obj.get("replenishmentId"),
            "creationDateTime": obj.get("creationDateTime"),
            "reference": obj.get("reference"),
            "labelingByBol": obj.get("labelingByBol"),
            "state": obj.get("state"),
            "deliveryInformation": DeliveryInformation.from_dict(obj["deliveryInformation"]) if obj.get("deliveryInformation") is not None else None,
            "pickupAppointment": PickupAppointment.from_dict(obj["pickupAppointment"]) if obj.get("pickupAppointment") is not None else None,
            "numberOfLoadCarriers": obj.get("numberOfLoadCarriers"),
            "loadCarriers": [LoadCarrier.from_dict(_item) for _item in obj["loadCarriers"]] if obj.get("loadCarriers") is not None else None,
            "lines": [ReplenishmentLine.from_dict(_item) for _item in obj["lines"]] if obj.get("lines") is not None else None,
            "invalidLines": [InvalidReplenishmentLine.from_dict(_item) for _item in obj["invalidLines"]] if obj.get("invalidLines") is not None else None,
            "stateTransitions": [StateTransition.from_dict(_item) for _item in obj["stateTransitions"]] if obj.get("stateTransitions") is not None else None
        })
        return _obj


