# coding: utf-8

"""
    v10 - Retailer API

    The bol.com API for retailers.  # Authentication Our API requires authentication via OAuth2. The detailed steps to authenticate are explained [here](https://api.bol.com/retailer/public/Retailer-API/authentication.html)   # Demo scenarios Our API specification includes examples of the responses you can expect. For more information as well as more examples, we refer you to the following resources:   - [Demo environment](https://api.bol.com/retailer/public/Retailer-API/demo/demo.html) - [Demo scenarios](https://api.bol.com/retailer/public/Retailer-API/demo/v10-index.html) 

    The version of the OpenAPI document: 10.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.update_delivery_info import UpdateDeliveryInfo
from openapi_client.models.update_load_carrier import UpdateLoadCarrier
from typing import Optional, Set
from typing_extensions import Self

class UpdateReplenishmentRequest(BaseModel):
    """
    UpdateReplenishmentRequest
    """ # noqa: E501
    state: Optional[StrictStr] = Field(default=None, description="Update the state of the replenishment to cancel the replenishment.")
    delivery_info: Optional[UpdateDeliveryInfo] = Field(default=None, alias="deliveryInfo")
    number_of_load_carriers: Optional[Annotated[int, Field(le=66, strict=True, ge=1)]] = Field(default=None, description="The number of parcels in this replenishment. Note: if you are using the bol.com pickup service, the maximum number is 20.", alias="numberOfLoadCarriers")
    load_carriers: Optional[Annotated[List[UpdateLoadCarrier], Field(min_length=1, max_length=66)]] = Field(default=None, alias="loadCarriers")
    __properties: ClassVar[List[str]] = ["state", "deliveryInfo", "numberOfLoadCarriers", "loadCarriers"]

    @field_validator('state')
    def state_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['CANCELLED']):
            raise ValueError("must be one of enum values ('CANCELLED')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateReplenishmentRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of delivery_info
        if self.delivery_info:
            _dict['deliveryInfo'] = self.delivery_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in load_carriers (list)
        _items = []
        if self.load_carriers:
            for _item in self.load_carriers:
                if _item:
                    _items.append(_item.to_dict())
            _dict['loadCarriers'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateReplenishmentRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "state": obj.get("state"),
            "deliveryInfo": UpdateDeliveryInfo.from_dict(obj["deliveryInfo"]) if obj.get("deliveryInfo") is not None else None,
            "numberOfLoadCarriers": obj.get("numberOfLoadCarriers"),
            "loadCarriers": [UpdateLoadCarrier.from_dict(_item) for _item in obj["loadCarriers"]] if obj.get("loadCarriers") is not None else None
        })
        return _obj


